### ISSUE TITLE
Suffix list not fetched over HTTPS

### ISSUE THREAD

**Issue by bgentry** [joeguo/tldextract#7]
I noticed that you're fetching the public suffix list [over HTTP](https://github.com/joeguo/tldextract/blob/d461054563ec6c66ad3478524aa8072a4e773b86/tldextract.go#L187).

Is there a reliable HTTPS URL you can use for this instead? For example, https://publicsuffix.org/list/effective_tld_names.dat

Thanks!

**Comment by joeguo** [comment]
fixed
