### ISSUE TITLE
tldextract doesn't work with internationalized domain names

### ISSUE THREAD

**Issue by lcosmin** [joeguo/tldextract#8]
The following code doesn't produce the expected result, due to `tldextract`'s code checking for letters/digits/dash in the resulting domain name:

```
package main
import (
"fmt"
"github.com/joeguo/tldextract"
)

func main() {
    cache := "/tmp/tld.cache"
    extract, _ := tldextract.New(cache, true)
    result:=extract.Extract("https://allestörungen.at/stoerung/upc/vienna")
    fmt.Printf("%+v\n",result)
}
```

**Comment by maganiss** [comment]
just fix the domainregex in `tldextract.go`:

```
domainregex = regexp.MustCompile(`^[a-z0-9-\p{L}]{1,63}$`)
```

note: `\p{Han}` for chinese has been replaced by to \p{L} to capture all unicode characters.
